### PR TITLE
Update render.js

### PR DESCRIPTION
**Pull request by ckreon**
Fix CSS issue in reference to #82.

### CODE REVIEW

**Comment by alanshaw** [comment]
Does this work with absolute paths as well as relative paths?

...so if i set the css path as `/home/alan/styles.css` or `c:\Users\alan\styles.css`?

**Comment by ckreon** [comment]
It should, but I can't test it properly to verify.

If it does cause issue, it may be worth implementing as an optional so Windows users can utilize as needed. This pull stemmed from your request in the comments of issue #82 - I submitted it because, for whatever reason, @bmahsman never did.

**Comment by alanshaw** [comment]
I think this needs consideration for relative paths and the OS (by the sounds of it in #82 this only applies to Windows) so I can't merge this as-is.

**Comment by ckreon** [comment]
I'll close this for now. It seems like @bmahsman is working on a proper PR with conditional application based on OS detection.

**Pull request closed without merging**
